export * from '@/modules/database/schema/modules/tb_windows_account'
export * from '@/modules/database/schema/modules/tb_windows_dept'
export * from '@/modules/database/schema/modules/tb_windows_kines'
export * from '@/modules/database/schema/modules/tb_windows_sheet'
export * from '@/modules/database/schema/modules/tb_windows_role'
export * from '@/modules/database/schema/modules/tb_windows_chunk'
export * from '@/modules/database/schema/modules/tb_windows_dept'
export * from '@/modules/database/schema/modules/tb_windows_role'
export * from '@/modules/database/schema/modules/tb_windows_position'
export * from '@/modules/database/schema/modules/tb_windows_rank'
export * from '@/modules/database/schema/modules/tb_windows_client'
export * from '@/modules/database/schema/modules/tb_windows_brand'
export * from '@/modules/database/schema/modules/tb_windows_currency'
/**短信服务表**/
export * from '@/modules/database/schema/sms/tb_sms_app'
export * from '@/modules/database/schema/sms/tb_sms_app_quotation'
export * from '@/modules/database/schema/sms/tb_sms_app_tasks'
export * from '@/modules/database/schema/sms/tb_sms_app_record'
