export * from '@web-windows-server/interface/common/auth.resolver'
export * from '@web-windows-server/interface/common/chunk.resolver'
export * from '@web-windows-server/interface/system/account.resolver'
export * from '@web-windows-server/interface/system/resource.resolver'
export * from '@web-windows-server/interface/system/role.resolver'
export * from '@web-windows-server/interface/system/dept.resolver'
