export * from '@/modules/database/system/tb_system_chunk'
export * from '@/modules/database/system/tb_system_kines'
export * from '@/modules/database/system/tb_system_user'
export * from '@/modules/database/system/tb_system_router'
export * from '@/modules/database/system/tb_system_role'
export * from '@/modules/database/system/tb_system_dept'
