export * from '@web-system-service/interface/system/system-user.resolver'
export * from '@web-system-service/interface/system/system-role.resolver'
export * from '@web-system-service/interface/system/system-chunk.resolver'
export * from '@web-system-service/interface/system/system-router.resolver'
export * from '@web-system-service/interface/system/system-dept.resolver'
